name             'ambari'
maintainer       ''
maintainer_email ''
license          ''
description      'Installs/Configures ambari'
long_description 'Installs/Configures ambari'
version          '0.1.0'

depends "selinux", '~> 0.8.0'
depends 'hostsfile'