name             'hds'
maintainer       ''
maintainer_email ''
license          ''
description      'Installs/Configures hds'
long_description 'Installs/Configures hds'
version          '0.1.0'

depends 'selinux'
depends 'hostsfile'
depends 'yum'
